# Generated by Django 5.2.1 on 2025-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_thumbnail_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_processing',
            field=models.BooleanField(default=False),
        ),
    ]
